muxiwebsite/profile/forms.py
# coding: utf-8
from flask_wtf import Form
from wtforms import StringField, SubmitField, TextAreaField, BooleanField,SelectField
from wtforms.validators import Required


class EditForm(Form):
    """
    用户个人信息编辑表单
    """
    username = StringField('username', validators=[Required()])
    avatar_url = StringField('avatar_url', validators=[Required()])
    info =  TextAreaField('info', validators=[Required()])

    email = StringField('email')
    birthday = StringField('birthday')
    hometown = StringField('hometown')
    group = SelectField('group',choices=[('backend','后台'),('frontend','前端'),('android','android'),('product','产品'),('design','设计')])
    timejoin = StringField('timejoin')
    timeleft = StringField('timeleft')
    left = BooleanField('left')

    personal_blog = StringField('personal_blog')
    github = StringField('github')
    flickr = StringField('flickr')
    weibo = StringField('weibo')
    zhihu = StringField('zhihu')

muxiwebsite/profile/__init__.py
# coding: utf-8

from flask import Blueprint

profile = Blueprint(
    'profile',
    __name__,
    template_folder = 'templates',
    subdomain = 'profile',
    static_folder = 'static'
)

from . import views, forms

muxiwebsite/profile/views.py
# coding: utf-8
"""
    views.py
    ~~~~~~~~

    木犀个人页视图

"""

from . import profile
from flask import render_template, url_for, redirect, request, flash
from flask_login import login_required
from flask_login import current_user
from ..models import User, Book
from .forms import EditForm
from muxiwebsite import db
import datetime


@profile.route('/<int:id>/', methods=["POST", "GET"])
@login_required
def user_profile(id):
    """
    ex: /profile/1/
    木犀个人页
    """


    date = datetime.date.today().strftime('%Y%m%d')[:4]
    user = User.query.get_or_404(id)
    user.avatar = user.avatar_url
    blogs = user.blogs
    for blog in blogs:
        blog.address = url_for('blogs.post', id=blog.id)

    books = user.book
    book_length = 0
    #return render_template("test.html", books=books)
    for book in books:
        book.title = book.name
        book.date = book.end
        book_length += 1

    shares = user.share # topic, author, contents
    for share in shares:
        share.topic = share.title
        share.author = user.username
        share.contents = share.share[:10]

    if request.method == 'POST':
        for iid in request.form.values():
            book = Book.query.get_or_404(iid)
            book.status = False
            book.start = None
            book.end = None
            book.user_id = None
        return redirect(url_for('profile.user_profile', id=current_user.id))

    if int(current_user.id) == int(user.id):
        owner = True
    else:
        owner = False

    return render_template(
        "pages/user.html",
        user=user,
        blogs=blogs,
        books=books,
        book_length=book_length,
        shares=shares,
        current_user=current_user,
        date=date,
        owner=owner
    )


@profile.route('/<int:id>/edit/', methods=['GET', 'POST'])
def edit(id):
    """
    编辑个人页
    """
    date = datetime.date.today().strftime('%Y%m%d')[:4]
    user = User.query.filter_by(id=current_user.id).first()
    form = EditForm()
    if form.validate_on_submit():

        # must fill in
        user.username = form.username.data
        user.avatar_url = form.avatar_url.data
        user.info = form.info.data

        user.email = form.email.data
        user.birthday = form.birthday.data
        user.hometown = form.hometown.data
        user.group = form.group.data
        user.timejoin = form.timejoin.data
        user.timeleft = form.timeleft.data
        user.left = form.left.data

        # social networks' urls
        user.personal_blog = form.personal_blog.data
        user.github = form.github.data
        user.flickr = form.flickr.data
        user.weibo = form.weibo.data
        user.zhihu = form.zhihu.data

        db.session.add(user)
        db.session.commit()
        return redirect(url_for('profile.user_profile', id=current_user.id))

    form.username.data = user.username
    form.avatar_url.data = user.avatar_url
    form.info.data = user.info
    form.email.data = user.email
    form.birthday.data = user.birthday
    form.hometown.data = user.hometown
    form.group.data = user.group
    form.timejoin.data = user.timejoin
    form.timeleft.data = user.timeleft
    form.left.data = user.left

    form.personal_blog.data = user.personal_blog
    form.github.data = user.github
    form.flickr.data = user.flickr
    form.weibo.data = user.weibo
    form.zhihu.data = user.zhihu

    return render_template('/pages/edit.html', form=form, date=date)

muxiwebsite/profile/templates/components/info.html
<div class="info margin_auto">
	<div class="head margin_auto">
		<img src="{{ user.avatar }}" class="avatar">
	</div>
	<div class="name">
		<a>{{ user.username }}</a>
	</div>
	<div class="small-circle margin_auto"></div>
	<div class="user-info margin_auto">
		<div>家乡:{{ user.hometown }}</div>
		<div>生日:{{ user.birthday }}</div>
		<div>组别:{{ user.group }}</div>
		<div>加入时间:{{ user.timejoin }}</div>
		{% if user.left %}
			<div>离开时间:{{ user.timeleft }}</div>
		{% endif %}
		<div>邮箱:{{ user.email }}</div>
		<div>个人介绍:{{ user.info }}</div>
	</div>
	<div class="link margin_auto space">
			<li class="front img va_item"></li>
			<li class="pic-1 img va_item">
                <a href={{ user.personal_blog }}></a>
			</li>
			<li class="pic-2 img va_item">
                <a href={{ user.github }}></a>
			</li>
			<li class="pic-3 img va_item">
                <a href={{ user.flickr }}></a>
			</li>
			<li class="pic-4 img va_item">
                <a href={{ user.weibo }}></a>
			</li>
			<li class="pic-5 img va_item">
                <a href={{ user.zhihu }}></a>
			</li>
			<li class="end img va_item"></li>
	</div>
</div>

muxiwebsite/profile/templates/components/list.html
<div class="list margin_auto">
	<div class="left">
		<div class="book topic">
            <a href="{{ url_for('books.home') }}"><span>木犀图书</span></a>
		</div>
		<form action="" method="POST" accept-charset="utf-8" class="form">
		{% for book in books %}
		<div class="td">
			<div class="title">
				<a href="{{ url_for('books.info', id=book.id) }}" class="title-link">《{{ book.name }}》</a>
			</div>
			<div class="date">归还日：{{ book.end[0:4]+'-'+book.end[4:6]+'-'+book.end[6:] }}</div>
			{% if current_user.id == user.id %}
			<input type="checkbox"  value={{ book.id }} name={{ book.id }} class="btn-checkbox"></input>
			{% endif %}
		</div>
		{% endfor %}
		{% if owner and book_length > 0%}
		<input type="submit" class="btn-return" value="确认还书"></input>
		{% endif %}
		</form>
	</div>
	<div class="middle">
		<div class="share margin_auto topic">
			<a href="{{ url_for('shares.index') }}"><span>分享链接</span></a>
		</div>
		{% for share in shares[-4:] %}
			<div class="title">
				<a href="{{ url_for('shares.view_share', id=share.id) }}" class="title-link">{{ share.title }}
				</a>
			</div>
			<div class="comments">
				{% for comment in share.comment[-2:] %}
				<div class="comments_lists">
					{{ comment.author_name }}//{{ comment.comment }}
				</div>
				{% endfor %}
			</div>
		{% endfor %}
	</div>
	<div class="right">
		<div class="blog topic">
			<span>博客链接</span>
		</div>
		<ol class="lists">
			{% for blogs in blogs %}
			<li>
				<a href="{{ blogs.address }}" class="address-link">
					{{ blogs.address }}
				</a>
			</li>
			{% endfor %}
		</ol>
	</div>
</div>

muxiwebsite/profile/templates/components/nav.html
<div class="nav">
	<div class="btn cp" id="nav-btn"></div>
	<div class="pop hide">
		<div class="cancel cp"></div>
		<a href="http://muxistudio.com" class="link">木犀团队主页</a>
		<a href="#" class="link">木犀团队博客</a>
		<a href="{{ url_for('books.home') }}" class="link">木犀图书馆</a>
		<!-- 下面的链接指向个人编辑页面 -->
		{% if current_user.id == user.id %}
        <a href={{ url_for("profile.edit", id=current_user.id) }} class="link">编辑个人资料</a>
        {% endif %}
	</div>
</div>