muxiwebsite/share/forms.py
# coding: utf-8


"""
    forms.py
    ~~~~~~~~

        muxishare表单文件

"""

from flask_wtf import Form
from wtforms.fields import StringField, SubmitField, TextAreaField, RadioField
from wtforms.validators import Required
from flask_pagedown.fields import PageDownField


class ShareForm(Form):
    """分享表单 markdown编辑器"""
    title = TextAreaField(validators=[Required()])
    # tag format ('<input value>', '<label display>')
    tag = RadioField('tag', choices=[
                ('frontend','frontend'),
                ('backend','backend'),
                ('android', 'android'),
                ('design', 'design'),
                ('product', 'product')
                ], validators=[Required()])
    share = PageDownField(validators=[Required()])
    submit = SubmitField('分享')


class CommentForm(Form):
    """评论表单, 一般的表单"""
    comment = TextAreaField(validators=[Required()])
    submit = SubmitField('评论')


class EditForm(Form):
    """编辑表单"""
    title = TextAreaField(validators=[Required()])
    tag = RadioField('tag', choices=[
        ('frontend', 'frontend'),
        ('backend', 'backend'),
        ('android', 'android'),
        ('design', 'design'),
        ('product', 'product')
        ])
    share = PageDownField(validators=[Required()])
    submit = SubmitField('修改')

muxiwebsite/share/__init__.py
# coding: utf-8

"""
    muxishare ~ 木犀团队的分享小站

        分享，是木犀的团队精神，这个小站类似于v2ex，不过分享者都是
        团队中的朋友，这会不一样 ~ ~ ~
"""

from flask import Blueprint

shares = Blueprint(
    'shares',
    __name__,
    subdomain='share',
    template_folder = 'templates',
    static_folder = 'static'
)


from . import views, forms , upload


"""
muxistudio bugday 2015年10月16日
"""

muxiwebsite/share/views.py
# coding: utf-8

"""
    views.py ~ 木犀分享视图文件

        主页: 发布分享

        /:  主页
        /share:  发布分享的页面
        /login:  登录页
        /logout: 登出页
        /new: 显示最新分享
        /hot: 显示最热分享
        /view_share: 查看分享的具体信息，评论，发表评论
"""

# models import
from . import shares
from jinja2 import Environment
from .forms import ShareForm, CommentForm, EditForm
from .. import  db, app
from ..models import Share, Comment, User, Permission
from flask import url_for, render_template, redirect, request, current_app, Markup , jsonify , g
from flask_login import current_user, login_required
from ..decorators import permission_required , login_required , version_required , tojson
from ..login import Login
from ..signup import Signup
from sqlalchemy import desc
from sqlalchemy import func
import markdown
import json
import requests
import os
import pickle
from qiniu import Auth, put_file, etag, urlsafe_base64_encode
import ast
from muxiwebsite import rds


tags2 = {'frontend' : ' 前端', 'backend' : '后端', 'android':'安卓','design':'设计','product':'产品'}
tags = ['frontend', 'backend', 'android', 'design', 'product']

@shares.route('/')
def index():
    """
    muxi_share 分享你的知识
	主页，默认显示最新的分享
	添加分页，默认显示第一页
    """

    flag = 0
    # 添加分页, share变为分页对象
    page = int(request.args.get('page') or 1)
    shares_count = {}
    # tags = ['frontend', 'backend', 'android', 'design', 'product']

    sort_arg = request.args.get('sort')
    if sort_arg == None:
        shares_pages = Share.query.order_by('-id').paginate(page, app.config['SHARE_PER_PAGE'], False)
        shares = shares_pages.items

    elif sort_arg == "new":
        flag = 0
        shares_pages = Share.query.order_by('-id').paginate(page, app.config['SHARE_PER_PAGE'], False)
        shares = shares_pages.items

    elif sort_arg == "hot":
        flag = 1
        shares = []
        for share in Share.query.all():
            shares_count[share] = share.comment.count()
        shares_count = sorted(shares_count.items(), lambda x, y: cmp(y[1], x[1]))
        for share_tuple in shares_count:
            shares.append(share_tuple[0])
        shares = shares[:5]
        shares_pages = None

    elif sort_arg in tags:
        flag = tags.index(sort_arg) + 2
        shares = []
        this_arg =  Share.query.filter_by(tag=sort_arg)
        shares_pages = this_arg.order_by('-id').paginate(page, app.config['SHARE_PER_PAGE'], False)
        shares = shares_pages.items


    for share in shares:
        share.avatar = User.query.filter_by(id=share.author_id).first().avatar_url
        share.comment_count = share.comment.count()
        share.author_id = share.author_id
        share.author = User.query.filter_by(id=share.author_id).first().username
        try :
            share.share = pickle.loads(share.share)
        except  :
            print "Share key value"
        try :
            share.title = pickle.loads(share.title)
        except :
            print "Title can not loads"

    return render_template('share_index.html', tags = tags, shares=shares, flag=flag, Permission=Permission, shares_pages=shares_pages)


@shares.route('/view/<int:id>/', methods=["GET", "POST"])
def view_share(id):

    """
    显示特定id的分享，相关信息以及评论
    实现评论表单发表自己的评论
    """
    share = Share.query.get_or_404(id)
    share.author = User.query.filter_by(id=share.author_id).first().username
    comments = Comment.query.filter_by(share_id=share.id).all()
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(
            comment = form.comment.data,
            author_id = current_user.id,
            author_name = User.query.filter_by(id=current_user.id).first().username,
            share_id = id,
			count = 0
            )
        db.session.add(comment)
        db.session.commit()
        this_comment = Comment.query.filter_by(
			comment=form.comment.data,
			author_id=current_user.id,
			share_id = id,
			).first()
        this_comment.count += 1
        return redirect(url_for('shares.view_share', id=id))

    share.avatar =  User.query.filter_by(id=share.author_id).first().avatar_url
    share.comments = len(Comment.query.filter_by(share_id=share.id).all())

    for comment in comments:
        comment.avatar = User.query.filter_by(id=comment.author_id).first().avatar_url
        comment.username = User.query.filter_by(id=comment.author_id).first().username
        try :
            comment.content = pickle.loads(comment.comment)
        except  :
            print "Comment can not load"
            comment.content = comment.comment
    try :
        share.share = pickle.loads(share.share)
    except :
        print "Share can not load"
    try :
        share.title = pickle.loads(share.title)
    except  :
        print "Title can not load"

    return render_template(
        'share_second.html',
        form = form,
        share = share,
        comments = comments
        )


@login_required
@shares.route('/send/', methods=["GET", "POST"])
def add_share():
    """
    分享
    """
    form = ShareForm()
    if form.validate_on_submit():
        share = Share(
                title = form.title.data,
                share = form.share.data,
                tag = form.tag.data,
                author_id = current_user.id
                )
        db.session.add(share)
        db.session.commit()
        share_tag = tags2[share.tag]
        try :
            title = pickle.loads(share.title)
        except  :
            title = share.title
            print "Title can not load"
        try :
            share_ = pickle.loads(share.share)
        except  :
            share_ = share.share
            print "Share can not load"

        link  = {
            "msgtype" : "link" ,
                "link" : {
                "title" : title ,
                "text" : share_[:10]  ,
                "picUrl": "" ,
                "messageUrl" : url_for("shares.view_share",id=share.id,_external=True) ,
                }
            }
        headers = { "Content-Type" : "application/json" }
        try :
            r = requests.post(current_app.config['SEND_URL'],data=json.dumps(link),headers=headers)
        except requests.exceptions.MissingSchema  :
            print "Wrong type URL"
        except requests.ConnectionError  :
            print "The URL is overdue"

        return redirect(url_for('.index', page = 1))
    return render_template("share_send.html", form=form, tags = tags)


@login_required
@shares.route('/delete/<int:id>/', methods=["GET", "POST"])
@permission_required(Permission.WRITE_ARTICLES)
def delete(id):
    """
    User could delete his share
    """
    share = Share.query.filter_by(id=id).first()
    db.session.delete(share)
    db.session.commit()
    return redirect(url_for("shares.index"))


@shares.route('/edit-share/<int:id>/', methods=["POST", "GET"])
@login_required
@permission_required(Permission.WRITE_ARTICLES)
def edit(id):
    """
    用户可以修改自己的分享
    """
    form = EditForm()
    share = Share.query.filter_by(id=id).first()
    if form.validate_on_submit():
        share.title = form.title.data
        share.share = form.share.data
        share.tag = form.tag.data
        db.session.add(share)
        db.session.commit()
        return redirect(url_for("shares.index", page=1))
    form.title.data = share.title
    form.share.data = share.share
    form.tag.data = share.tag
    return render_template(
            "edit-share.html",
            form = form,
            tags = tags
            )


@shares.route('/api/v2.0/all/', methods=['GET'])
def get_shares2():
    """
    获取所有分享
    """
    page = request.args.get('page', 1, type=int)
    pagination = Share.query.order_by('-id').paginate(
        page,
        per_page=current_app.config['MUXI_SHARES_PER_PAGE'],
        error_out=False
    )
    shares = pagination.items
    per_page = current_app.config['MUXI_SHARES_PER_PAGE']
    pages_count = pagination.total / per_page + 1
    if page > pages_count :
        return jsonify({}),  404
    shares_count = len(Share.query.all())

    return jsonify({
        'shares': [ share.to_json()  for share in shares ],
        'count': pagination.total ,
        'page' : page , # 当前页数
        'pages_count' : pages_count ,
    }), 200


@shares.route('/api/v2.0/<int:id>/comments/',methods=["GET"])
def view_share2(id) :
    '''
    查看某一篇分享的评论
    '''
    share = Share.query.get_or_404(id)
    comments = Comment.query.order_by('-id').filter_by(share_id=id).all()

    return jsonify({
        "comment" :  [ comment.to_json() for comment in comments ] ,
        "comment_num" : len(comments) ,
        }) ,200

@shares.route('/api/v2.0/<int:id>/add_comment/',methods=['POST'])
@login_required
def add_comment2(id) :
    '''
    登录用户发表评论
    '''
    share = Share.query.filter_by(id=id).first()
    share.read_num = 1
    share.comment_num += 1
    db.session.add(share)
    db.session.commit()
    comment = Comment()
    comment.comment = pickle.dumps(request.get_json().get("comment"))
    comment.share_id = id
    comment.author_id = g.current_user.id
    comment.author_name = g.current_user.username
    db.session.add(comment)
    db.session.commit()
    return jsonify({
        'message' : 'You add a comment successfully!'
        }) , 200


@shares.route('/api/v2.0/send/',methods=['POST'])
@login_required
def add_share2() :
    '''
    登录用户发送分享
    '''
    share = Share()
    share.title =  pickle.dumps(request.get_json().get("title"))
    share.share = pickle.dumps(request.get_json().get("share"))
    share.tag = request.get_json().get("tags")
    share.read_num = 0
    share.author_id = g.current_user.id
    db.session.add(share)
    db.session.commit()
    share_tag = tags2[share.tag]
    try :
        title = pickle.loads(share.title)
    except  :
        title = share.title
        print "title can not load in  api"
    try :
        share_ = pickle.loads(share.share)
    except  :
        share_ = share.share
        print "share can not load in api"

muxiwebsite/share/templates/edit-share.html
{% extends "share_base.html" %}
{% block head %}
{{ super() }}
<script type="text/javascript" src="{{ url_for("shares.index") }}/static/js/Markdown.Converter.min.js"></script>
<script type="text/javascript" src="{{ url_for("shares.index") }}/static/js/Markdown.Sanitizer.min.js"></script>
{% endblock%}
{% block title %}
<title>木犀分享-编辑分享</title>
{% endblock %}
{% block content %}
<section class="section_center">
    <div class="send_card mdl-card mdl-shadow--2dp">
        <form method="post">
            {{ form.hidden_tag() }}
            {{ form.title(class="send_title" ) }}
            <div class="send_tag">
                {% for tag in tags %}
                <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="option-{{loop.index}}">
                    <input type="radio" id="option-{{ loop.index }}" class="mdl-radio__button" name="tag" value="{{ tag }}">
                    <span class="mdl-radio__label">{{ tag | capitalize }}</span>
                </label>
                {% endfor %}
            </div>
            <div class="send_content mdl-grid mdl-grid--no-spacing">
                {{ form.share }}
            </div>
            <div class="mdl-card__actions mdl-card--border">
                <button  type="submit" class="send_submit_btn mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--raised">
                    EDIT
                </button>
            </div>
        </form>

    </div>
</section>
{% endblock %}

muxiwebsite/share/templates/error415.html
<!DOCTYPE html> 
<title>415 Unsupported Media Type</title>
<h1>415 Unsupported Media Type</h1>
<body>对于当前请求的方法和所请求的资源，请求中提交的实体并不是服务器中所支持的格式，因此请求被拒绝。</body>

muxiwebsite/share/templates/share_base.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}
        <meta http-equiv='x-dns-prefetch-control' content='on'>
        <link rel='dns-prefetch' href='http://7xtb8m.com1.z0.glb.clouddn.com'>
        <link rel="stylesheet" href="/static/css/material.min.css">
        <link rel="stylesheet" href="/static/css/icon.css">
        <link rel="stylesheet" href="/static/css/main.css">
        <link rel="icon" href="/static/images/share_128.ico" sizes="32x32">
        <link rel="icon" href="/static/images/share_128.ico" sizes="64x64">
        <link rel="icon" href="/static/images/share_128.ico" sizes="128x128">
    {% endblock %}
    {% block title %}
    {% endblock %}
</head>

<body class="mdl-color--grey-100">
    {% include 'share_header.html' %}
    {% block content %}
    {% endblock %}
    {% include 'share_footer.html' %}
<script src="/static/js/material.min.js"></script>
</body>

</html>

muxiwebsite/share/templates/share_footer.html
<footer class="mdl-mini-footer footer">
  <div class="mdl-mini-footer__left-section">
    <div class="mdl-logo">Hello from Wuhan&nbsp;&nbsp;2014-2016 Muxistudio</div>
    <ul class="mdl-mini-footer__link-list">
        <li><a href="http://muxistudio.com">木犀博客</a></li>
        <li><a href="{{ url_for("books.home") }}">木犀图书</a></li>
    </ul>
  </div>
</footer>

muxiwebsite/share/templates/share_header.html
<header class="header">
    <div class="demo-layout-transparent mdl-layout mdl-js-layout mdl-layout--fixed-header" style="background: url('http://7xtb8m.com2.z0.glb.clouddn.com/share_bg_{{[1,2,3]|random}}.jpg') center/cover;">
        <header class="mdl-layout__header mdl-layout__header--transparent">
            <div class="mdl-layout__header-row">
                <!-- Title -->
                <span class="mdl-layout-title">
                    木犀分享
                </span>
                <!-- Add spacer, to align navigation to the right -->
                <div class="mdl-layout-spacer"></div>
                <!-- Navigation -->
                <nav class="mdl-navigation mdl-layout--large-screen-only">
                    <a class="mdl-navigation__link" href="{{ url_for("shares.index") }}">首页</a>
					{% if current_user.is_authenticated %}
                    <a class="mdl-navigation__link" href="{{ url_for("auth.logout") }}">登出</a>
					{% else %}
                    <a class="mdl-navigation__link" href="{{ url_for("auth.login") }}">登录</a>
					{% endif %}
                </nav>
            </div>
        </header>
        <div class="mdl-layout__drawer">
            <span class="mdl-layout-title">木犀分享</span>
            <nav class="mdl-navigation">
                <a class="mdl-navigation__link" href="{{ url_for("shares.index") }}">首页</a>
                {% if current_user.is_authenticated %}
                <a class="mdl-navigation__link" href="{{ url_for("auth.logout") }}">登出</a>
                {% else %}
                <a class="mdl-navigation__link" href="{{ url_for("auth.login") }}">登入</a>
                {% endif %}
            </nav>
        </div>
        <main class="mdl-layout__content">
        </main>
    </div>
</header>

muxiwebsite/share/templates/share_index.html
{% extends "share_base.html" %} {% block title %}
<title>木犀分享</title>
{% endblock %} {% block content %}
<div class="mdl-tabs mdl-js-tabs mdl-js-ripple-effect tab_bar">
    {% if current_user.is_authenticated %}
    <a href="/send" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored btn_add">
        <i class="material-icons">add</i>
    </a>
    {% endif %}
    <div class="mdl-tabs__tab-bar" id="header_tab_bar">
        <a href="#" class="mdl-tabs__tab {% if flag == 0 %}is-active{% endif%} header_tabs">NEW</a>
        <a href="#" class="mdl-tabs__tab header_tabs {% if flag == 1 %}is-active{% endif%} ">HOT</a>
        <a href="#" class="mdl-tabs__tab header_tabs">MINE</a>
        <a href="#" class="mdl-tabs__tab header_tabs {% if flag == 2 %}is-active{% endif%} ">FRONTEND</a>
        <a href="#" class="mdl-tabs__tab header_tabs {% if flag == 3 %}is-active{% endif%} ">BACKEND</a>
        <a href="#" class="mdl-tabs__tab header_tabs {% if flag == 4 %}is-active{% endif%} ">ANDROID</a>
        <a href="#" class="mdl-tabs__tab header_tabs {% if flag == 5 %}is-active{% endif%} ">DESIGN</a>
        <a href="#" class="mdl-tabs__tab header_tabs {% if flag == 6 %}is-active{% endif%} ">PRODUCT</a>
    </div>
    <a href="/?page=1&sort=new" class="header_tab_links " style="display:none"></a>
    <a href="/?page=1&sort=hot" class="header_tab_links" style="display:none"></a>
    {% if current_user.is_authenticated %}
    <a href="{{ url_for("profile.user_profile", id=current_user.id) }}" class="header_tab_links" style="display:none"></a>
    {% else %}
    <a href="{{ url_for("auth.login") }}" class="header_tab_links" style="display:none"></a>
    {% endif %}
    <a href="/?page=1&sort=frontend" class="header_tab_links " style="display:none"></a>
    <a href="/?page=1&sort=backend" class="header_tab_links" style="display:none"></a>
    <a href="/?page=1&sort=android" class="header_tab_links " style="display:none"></a>
    <a href="/?page=1&sort=design" class="header_tab_links" style="display:none"></a>
    <a href="/?page=1&sort=product" class="header_tab_links" style="display:none"></a>
</div>
<section class="section_center">
    {% for share in shares %}
    <div class="index_card mdl-card mdl-cell mdl-cell--12-col">
        <div class="card_inner mdl-grid mdl-grid--no-spacing">
            <div class="mdl-cell mdl-cell--12-col">
                <h2 class="card_title">{{ share.title }}</h2>
            </div>
            <div class="mdl-cell mdl-cell--2-col mdl-cell--1-col-phone">
                <a class="card_circle mdl-color--primary"
                id={{'share_' + loop.index|string()}} href="{{ url_for("profile.user_profile", id=share.author_id) }}">
                    <img src={{ share.avatar }} alt="avatar">
                </a>
                <div class="mdl-tooltip" for={{'share_' + loop.index|string()}}>
                    {{ share.author }}
                </div>
            </div>
            <div class="card_text mdl-cell mdl-cell--10-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
                {{ share.share[:100]|neomarkdown }}
            </div>
        </div>
        <div class=" mdl-grid mdl-grid--no-spacing mdl-card__actions card_action">
            <div class="card_action_btn mdl-cell mdl-cell--4-col">
                <i class="material-icons mdl-color-text--grey mdl-badge card_icon" data-badge={{ share.comment_count }}>message</i>
                <i class="material-icons mdl-color-text--grey card_icon">favorite</i>
                <span class="mdl-chip card_icon">
                    <span class="mdl-chip__text"> {{ share.tag }}</span>
                </span>
            </div>
            <div class="card_more mdl-cell mdl-cell--8-col">
                <a href="{{ url_for("shares.view_share", id=share.id) }}" class="mdl-button mdl-js-button  mdl-js-ripple-effect">Read More</a>
				{% if share.author_id == current_user.id %}
                <a href="{{ url_for("shares.edit", id=share.id) }}" class="mdl-button mdl-js-button  mdl-js-ripple-effect">edit</a>
                <a href="{{ url_for("shares.delete", id=share.id) }}" class="mdl-button mdl-js-button  mdl-js-ripple-effect">delete</a>
				{% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
	<div class="pager">
        <div class="pager_container prev_container">
        {% if shares_pages.has_prev %}
            <a href="{{ url_for('shares.index', page = shares_pages.prev_num, sort=request.args.get('sort')) }}" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
                <i class="material-icons">arrow_back</i>
            </a>
             {% endif %}
        </div>
        <div class="pager_container forward_container">
        {% if shares_pages.has_next %}
            <a href="{{ url_for('shares.index', page = shares_pages.next_num, sort=request.args.get('sort')) }}" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
                <i class="material-icons">arrow_forward</i>
            </a>
             {% endif %}
		</div>
	</div>
</section>
<script src="/static/js/index.min.js"></script>
{% endblock %}

muxiwebsite/share/templates/share_second.html
{% extends "share_base.html" %} {% block title %}
<title>木犀分享-详情</title>
{% endblock %} {% block content %}
<section class="section_center">
    <div class="index_card mdl-card mdl-cell mdl-cell--12-col mdl-card mdl-shadow--2dp">
        <div class="card_inner mdl-grid mdl-grid--no-spacing">
            <div class="mdl-cell mdl-cell--12-col">
                <h2 class="card_title">{{ share.title }}</h2>
            </div>
            <div>
                {{ share.tag }}
            </div>
            <div class="mdl-cell mdl-cell--2-col mdl-cell--1-col-phone">
                <div class="card_circle mdl-color--primary">
                    <img src="{{ share.avatar}}" alt="avatar" id="author">
                </div>
                 <div class="mdl-tooltip" for="author">
                    {{ share.author }}
                </div>
            </div>
            <div class="card_text mdl-cell mdl-cell--10-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
                {{ share.share|neomarkdown }}
            </div>
        </div>
        <div class=" mdl-grid mdl-grid--no-spacing mdl-card__actions card_action">
            <div class="card_action_btn mdl-cell mdl-cell--2-col">
                <i class="material-icons mdl-color-text--grey mdl-badge" data-badge="{{ share.comments }}">message</i>
                <i class="material-icons mdl-color-text--grey">favorite</i>
            </div>
            <div class="card_more mdl-cell mdl-cell--10-col">
            </div>
        </div>
    </div>
    <div class="mdl-card mdl-cell mdl-cell--12-col mdl-card mdl-shadow--2dp">
        <div class="second_comments mdl-grid mdl-grid--no-spacing">
            <h4 class="mdl-cell mdl-cell--12-col second_comments_h4">Comments</h4> 
            {% for comment in comments %}
            <div class="mdl-cell mdl-cell--2-col mdl-cell--1-col-phone">
                <div class="card_circle ">
                    <img src="{{ comment.avatar}}" alt="{{ comment.username }}"
                    id={{'comment_' + loop.index|string()}}>
                </div>
                <div class="mdl-tooltip" for={{'comment_' + loop.index|string()}}>
                    {{ comment.username }}
                </div>
            </div>
            <div class="second_comments_content mdl-cell mdl-cell--10-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
                {{ comment.content }}
            </div>
            {% endfor %}
            {% if current_user.is_authenticated %}
             <h4 class="mdl-cell mdl-cell--12-col second_comments_h4 padding_t_30">Add New Comments</h4> 
            <form method="post" class="comment_form">
                {{ form.hidden_tag() }}
                <div class="mdl-textfield mdl-js-textfield comment_ta">
                    {{ form.comment(class="mdl-textfield__input") }} 
                    <label class="mdl-textfield__label" for="sample5">Comment here...</label>
                </div>
                {{ form.submit(class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--raised",value="提交")}}
            </form>
            {% endif %} 
        </div>
    </div>
</section>
{% endblock %}

muxiwebsite/share/templates/share_send.html
{% extends "share_base.html" %}
{% block head %}
    {{ super() }}
{% endblock%}
{% block title %}
<title>木犀分享-新分享</title>
{% endblock %}
{% block content %}
<section class="section_center">
    <div class="send_card mdl-card mdl-shadow--2dp">
        <form method="post">
            {{ form.hidden_tag() }}
            {{ form.title(class="send_title", placeholder="分享主题") }}
            <div class="send_tag">
                {% for tag in tags %}
                <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="option-{{loop.index}}">
                    <input type="radio" id="option-{{ loop.index }}" class="mdl-radio__button" name="tag" value="{{ tag }}">
                    <span class="mdl-radio__label">{{ tag | capitalize }}</span>
                </label>
                {% endfor %}
            </div>
            <div class="send_content mdl-grid mdl-grid--no-spacing">
                {{ form.share }}
            </div>
            <div class="mdl-card__actions mdl-card--border">
                <button  type="submit" class="send_submit_btn mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--raised">
                SHARE
                </button>
            </div>
        </form>
    </div>
</section>
<div id="demo-snackbar-example" class="mdl-js-snackbar mdl-snackbar">
  <div class="mdl-snackbar__text"></div>
  <button class="mdl-snackbar__action" type="button"></button>
</div>
<script type="text/javascript" src="/static/js/send.js"></script>
<script type="text/javascript" src="http://7xtb8m.com1.z0.glb.clouddn.com/Markdown.Converter.min.js"></script>
<script type="text/javascript" src="http://7xtb8m.com1.z0.glb.clouddn.com/Markdown.Sanitizer.min.js"></script>
{% endblock %}

muxiwebsite/share/templates/upload.html
<!DOCTYPE html> 
    <title>Upload Picture</title> 
    <h1>Upload </h1> 
    <form action = "" method = "post" enctype=multipart/form-data> 
		<input type = "file" name = file > 
        <input type = "submit" value = Upload> 
	</form> 