muxiwebsite/i/__init__.py
# coding: utf-8

"""
    i.muxixyz.com

        内部官网

        site: http://lib.muxistudio.com
        code: flask + html + css + js
"""

from flask import Blueprint


i = Blueprint(
    'i',
    __name__,
    template_folder = 'templates',
    static_folder = 'static',
    subdomain = 'i'
)


from . import views

muxiwebsite/i/views.py
# coding: utf-8

from . import i
from flask import render_template, redirect, url_for, request
from flask_login import login_required, current_user
from muxiwebsite.models import User


@i.route('/')
@login_required
def index():
    """
    木犀博客首页
    """
    return render_template("index.html", current_user=current_user)


@i.route('/members/')
@login_required
def members():
    """
    Show all members
    """
    users = User.query.all()

    # Group mambers' list initialization
    frontends = []
    backends = []
    androids = []
    designs = []
    products = []

    for user in users:
        if user.left == False:
            if user.group == 'frontend':
                frontends.append(user)
            elif user.group == 'backend':
                backends.append(user)
            elif user.group == 'android':
                androids.append(user)
            elif user.group == 'design':
                designs.append(user)
            elif user.group == 'product':
                products.append(user)

    return render_template(
            "members.html",
            frontends = frontends,
            backends = backends,
            androids = androids,
            designs = designs,
            products = products,
            current_user = current_user
            )

muxiwebsite/i/templates/i_base.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}
        <link rel="stylesheet" href="/static/css/material.min.css">
        <link rel="stylesheet" href="/static/css/main.css">
        <link rel="icon" href="http://muxistudio.com/static/images/favicon/favicon-32x32.png" sizes="32x32">
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="mdl-layout mdl-js-layout">
        <header class="mdl-layout__header mdl-layout__header--scroll portfolio-header">
            <div class="mdl-layout__header-row portfolio-logo-row">
                <span class="mdl-layout__title">
                    <div class="portfolio-logo"></div>
                    <span class="mdl-layout__title">木犀团队内网</span>
                </span>
            </div>
            <div class="mdl-layout__header-row portfolio-navigation-row mdl-layout--large-screen-only">
                <nav class="mdl-navigation mdl-typography--body-1-force-preferred-font">
                    <a class="mdl-navigation__link is-active" href="{{ url_for("i.index" )}}">Welcome</a>
                    <a class="mdl-navigation__link" href="https://github.com/Muxi-Studio">Github</a>
                    <a class="mdl-navigation__link" href="http://weibo.com/ccnumuxistudio">Sina Weibo</a>
                    {% if current_user.is_authenticated %}
                        <a class="mdl-navigation__link" href="{{ url_for("auth.logout") }}">Logout</a>
                    {% else %}
                        <a class="mdl-navigation__link" href="{{ url_for("auth.login") }}">Login</a>
                    {% endif %}
                </nav>
            </div>
        </header>
        <div class="mdl-layout__drawer mdl-layout--small-screen-only">
            <nav class="mdl-navigation mdl-typography--body-1-force-preferred-font">
                <a class="mdl-navigation__link is-active" href="{{ url_for("i.index") }}">Welcome</a>
                <a class="mdl-navigation__link" href="https://github.com/Muxi-Studio">Github</a>
                <a class="mdl-navigation__link" href="http://weibo.com/ccnumuxistudio">Sina Weibo</a>
                {% if current_user.is_authenticated%}
                    <a class="mdl-navigation__link" href="{{ url_for("auth.logout") }}">Logout</a>
                {% else %}
                    <a class="mdl-navigation__link" href="{{ url_for("auth.login") }}">Login</a>
                {% endif %}
            </nav>
        </div>
        <main class="mdl-layout__content">
            {% block content %}
            {% endblock %}
            <div class="mdl-layout-spacer"></div>
            <footer class="mdl-mini-footer">
                <div class="mdl-mini-footer__left-section">
                    <div class="mdl-logo">Hello from Wuhan Muxistudio</div>
                </div>
            </footer>
        </main>
    </div>
<script src="/static/js/material.min.js"></script>
</body>

</html>

muxiwebsite/i/templates/index.html
{% extends "i_base.html" %} 
{% block title %}木犀内网{% endblock %}
{% block content %}
    <div class="mdl-grid portfolio-max-width">
        <div class="mdl-cell mdl-card mdl-shadow--4dp portfolio-card">
            <div class="mdl-card__media article-img-bg">
                <img class="article-image" src="http://muxistudio.com/static/images/main.svg" border="0" alt="">
            </div>
            <div class="mdl-card__title">
                <h2 class="mdl-card__title-text">木犀官网</h2> </div> <div class="mdl-card__actions mdl-card--border">
                <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect mdl-button--accent" href="http://muxistudio.com/">点击进入</a>
            </div>
        </div>
        <div class="mdl-cell mdl-card mdl-shadow--4dp portfolio-card">
            <div class="mdl-card__media">
                <img class="article-image" src="/static/images/library.png" border="0" alt="">
            </div>
            <div class="mdl-card__title">
                <h2 class="mdl-card__title-text">木犀图书</h2>
            </div>
            <div class="mdl-card__actions mdl-card--border">
                <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect mdl-button--accent" href="{{ url_for("books.home") }}">点击进入</a>
            </div>
        </div>
        <div class="mdl-cell mdl-card mdl-shadow--4dp portfolio-card">
            <div class="mdl-card__media">
                <img class="article-image" src="/static/images/share.png" border="0" alt="">
            </div>
            <div class="mdl-card__title">
                <h2 class="mdl-card__title-text">木犀分享</h2>
            </div>
            <div class="mdl-card__actions mdl-card--border">
                <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect mdl-button--accent" href="{{ url_for("shares.index") }}">点击进入</a>
            </div>
        </div>
        <div class="mdl-cell mdl-card mdl-shadow--4dp portfolio-card">
            <div class="mdl-card__media">
                <img class="article-image" src="/static/images/example-blog02.jpg" border="0" alt="">
            </div>
            <div class="mdl-card__title">
                <h2 class="mdl-card__title-text">木犀博客</h2>
            </div>
            <div class="mdl-card__actions mdl-card--border">
                <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect mdl-button--accent" href="{{ url_for("blogs.index") }}">点击进入</a>
            </div>
        </div>
        <div class="mdl-cell mdl-card mdl-shadow--4dp portfolio-card">
            <div class="mdl-card__media">
                <img class="article-image" src="/static/images/example-work07.jpg" border="0" alt="">
            </div>
            <div class="mdl-card__title">
                <h2 class="mdl-card__title-text">我</h2>
            </div>
            <div class="mdl-card__actions mdl-card--border">
                {% if current_user.is_authenticated %}
                <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect mdl-button--accent" href="{{ url_for("profile.user_profile", id=current_user.id) }}">点击进入</a>
                {% else %}
                <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect mdl-button--accent" href="{{ url_for("auht.login") }}">点击进入</a>
                {% endif %}
            </div>
        </div>
        <div class="mdl-cell mdl-card mdl-shadow--4dp portfolio-card">
            <div class="mdl-card__media">
                <img class="article-image" src="/static/images/example-work08.jpg" border="0" alt="">
            </div>
            <div class="mdl-card__title">
                <h2 class="mdl-card__title-text">团队成员</h2>
            </div>
            <div class="mdl-card__actions mdl-card--border">
                <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect mdl-button--accent" href="{{ url_for("i.members") }}">点击进入</a>
            </div>
        </div>
    </div>
{% endblock %}

muxiwebsite/i/templates/members.html
{% extends "i_base.html" %} 
{% block title %}木犀内网-团队成员{% endblock %}
{% block content %}
    <div class="avatar-title">前端组</div>
    <div class="mdl-grid profile-grid">
        {% for frontend in frontends %}
            <div class="mdl-cell mdl-card avatar-box">
                <div class="mdl-card__media avatar-card">
                    <div class="avatar">
                        <img class="avatar-img" src="{{ frontend.avatar_url }}">
                    </div>
                </div>
                <a class="username" href="{{ url_for("profile.user_profile", id=frontend.id) }}">{{ frontend.username }}</a>
            </div>
        {% endfor %}
    </div>
    <div class="avatar-title">后台组</div>
    <div class="mdl-grid profile-grid">
        {% for backend in backends %}
            <div class="mdl-cell mdl-card avatar-box">
                <div class="mdl-card__media avatar-card">
                    <div class="avatar">
                        <img class="avatar-img" src="{{ backend.avatar_url }}">
                    </div>
                </div>
                <a class="username" href="{{ url_for("profile.user_profile", id=backend.id) }}">{{ backend.username }}</a>
            </div>
        {% endfor %}
    </div>
    <div class="avatar-title">Android组</div>
    <div class="mdl-grid profile-grid">
        {% for android in androids %}
            <div class="mdl-cell mdl-card avatar-box">
                <div class="mdl-card__media avatar-card">
                    <div class="avatar">
                        <img class="avatar-img" src="{{ android.avatar_url }}">
                    </div>
                </div>
                <a class="username" href="{{ url_for("profile.user_profile", id=android.id) }}">{{ android.username }}</a>
            </div>
        {% endfor %}
    </div>
    <div class="avatar-title">设计组</div>
    <div class="mdl-grid profile-grid">
        {% for design in designs %}
            <div class="mdl-cell mdl-card avatar-box">
                <div class="mdl-card__media avatar-card">
                    <div class="avatar">
                        <img class="avatar-img" src="{{ design.avatar_url }}">
                    </div>
                </div>
                <a class="username" href="{{ url_for("profile.user_profile", id=design.id) }}">{{ design.username }}</a>
            </div>
        {% endfor %}
    </div>
    <div class="avatar-title">产品组</div>
    <div class="mdl-grid profile-grid">
        {% for product in products %}
            <div class="mdl-cell mdl-card avatar-box">
                <div class="mdl-card__media avatar-card">
                    <div class="avatar">
                        <img class="avatar-img" src="{{ product.avatar_url }}">
                    </div>
                </div>
                <a class="username" href="{{ url_for("profile.user_profile", id=product.id) }}">{{ product.username }}</a>
            </div>
        {% endfor %}
    </div>
{% endblock %}